chore: update dotfiles with minimal configuration

diff --git a/php/composer/install b/php/composer/install
--- a/php/composer/install
+++ b/php/composer/install
@@ -1,21 +1,17 @@
-#!/bin/bash
+#!/bin/sh
 
-EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
+EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
 php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
+ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
 
-if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
+if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
 then
-    >&2 echo 'ERROR: Invalid installer signature'
+    >&2 echo 'ERROR: Invalid installer checksum'
     rm composer-setup.php
     exit 1
 fi
 
-php composer-setup.php
+php composer-setup.php --quiet
 RESULT=$?
-
 rm composer-setup.php
-
-mv composer.phar /usr/local/bin/composer
-
 exit $RESULT
